server:
  port: 8088


spring:
  # 配置mysql,根据url自动识别Driver
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 13013005866
  #解决springboot不能处理put和delete请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#   这两个配置可删除mybatis-config.xml并且替代上面的配置
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  type-aliases-package: org.cold92.bean


